/***********************************************************************************************************************
 *  FILE DESCRIPTION
 *  ------------------------------------------------------------------------------------------------------------------*/
/** \file
 *  \brief        OSEK transport protocol version ISO-15765
 *  \description  This versions supports the specification for the OSEK transport protocol with the following
 *                restriction: Maximum message length is 255 byte for RX and TX (no length in TPCI).
 *
 *  --------------------------------------------------------------------------------------------------------------------
 *  COPYRIGHT
 *  --------------------------------------------------------------------------------------------------------------------
 *  \par Copyright
 *  \verbatim
 *  Copyright (c) 2017 by Vector Informatik GmbH.                                                  All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *                This software is only allowed to be used for and with the VECTOR Flash Bootloader!
 *  \endverbatim
 */
/**********************************************************************************************************************/

/***********************************************************************************************************************
 *  AUTHOR IDENTITY
 *  --------------------------------------------------------------------------------------------------------------------
 *  Name                          Initials      Company
 *  --------------------------------------------------------------------------------------------------------------------
 *  Christian Baeuerle            CB            Vector Informatik GmbH
 *  Konrad Lazarus                Ls            Vector Informatik GmbH
 *  Robert Schaeffner             Rr            Vector Informatik GmbH
 *  Quetty Palacios               QPs           Vector Informatik GmbH
 *  Marcel Viole                  MVi           Vector Informatik GmbH
 *  Andre Caspari                 Ci            Vector Informatik GmbH
 *  Thomas Bezold                 TBe           Vector Informatik GmbH
 *  Achim Strobelt                Ach           Vector Informatik GmbH
 *  Alexander Starke              ASe           Vector Informatik GmbH
 *  Torben Stoessel               TnS           Vector Informatik GmbH
 *  Marco Riedl                   Rie           Vector Informatik GmbH
 *  --------------------------------------------------------------------------------------------------------------------
 *  REVISION HISTORY
 *  --------------------------------------------------------------------------------------------------------------------
 *  Version    Date        Author  Change Id        Description
 *  --------------------------------------------------------------------------------------------------------------------
 *  03.00.00   2008-02-08  Hp      ESCAN00024337    Adapt configuration switches to match naming rules.
 *                                                  FTP_CFG.H now generated by GENy.
 *  03.00.01   2008-02-28  Hp      ESCAN00024955    Add optionally support to map TP-functions into RAM using memmap
 *                                                  Indicate useless configuration combination with
 *                                                  ISO15765-2.2/Overrun bit support and TOO_LARGE_DATA indication.
 *                                                  Correcting prototype for FblTpPrecopy on some configurations.
 *  03.01.00   2008-03-12  Rr      ESCAN00025302    Removed pragma for V850 with NEC compiler
 *                                 ESCAN00027212    No changes
 *  03.02.00   2008-06-05  QPs     ESCAN00027374    No changes
 *                         Ci      ESCAN00027409    Added support for configurations with multiple CAN channels
 *  03.02.01   2008-06-24  MVi     ESCAN00027820    No changes
 *  03.03.00   2008-11-18  AWh     ESCAN00031393    Allow configurations with both FblTp and TPMC, allow
 *                                                  alternative txDataBuffer and rxDataBuffer configurations.
 *  03.04.00   2009-05-18  Ci      ESCAN00032418    No changes
 *                         Ls      ESCAN00035170    renamed FBL_TP_DISABLE_V2XX_COMPATIBILITY
 *                         QPs     ESCAN00035243    Support for variable block size and STmin
 *  03.05.00   2009-08-13  Hp      ESCAN00037079    Call Confirmation within FblTpTransmitSF after transmission request
 *                                                  Remove CAN calls if COM wrapper is used.
 *  03.05.01   2009-09-10  Hp      ESCAN00037122    No changes here (see fbl_tp.c)
 *  03.06.00   2009-12-09  TBe     ESCAN00039383    No changes
 *  03.07.00   2010-02-16  AWh     ESCAN00040879    Adaptations to reduce compiler warnings, changed include order
 *                                                  for string.h/stddef.h, readded kTpTxHandle compatibility macro
 *  03.08.00   2010-10-14  Ci      ESCAN00044300    Added definition of tpCanTxData
 *                                                  for Vector CAN driver configurations
 *                         Hp      ESCAN00045954    TxTimer isn't reset after successful send repetition
 *  03.09.00   2012-01-23  AWh     ESCAN00054601    Added configuration to allow dynamic switch normal/extended addressing
 *  03.10.00   2012-05-25  Ach     ESCAN00057426    No changes
 *                         CB      ESCAN00059071    No changes
 *  03.11.00   2012-07-06  CB      ESCAN00059951    No changes
 *  03.12.00   2013-04-19  ASe     ESCAN00064581    Adapted comments to use Doxygen
 *                         Hp      ESCAN00066786    TpRx- and TpTx states splitted and simplified, separate var. for rxSN
 *                                 ESCAN00066792    Add support for queued requests
 *  03.12.01   2013-07-25  Hp      ESCAN00068861    Remove compile check INTERRUPT_CONFIRMATION with CAN_CONFIRMATION
 *                                                  for CBD-Driver usage
 *                                 ESCAN00069345    Separate FC-timer for FC.Wait transmission
 *  03.13.00   2015-07-15  AWh     ESCAN00084003    Beautification
 *  03.14.00   2015-08-18  QPs     ESCAN00084611    No changes
 *  03.14.01   2015-12-03  TnS     ESCAN00050252    No changes
 *  03.15.00   2016-02-19  Ach     ESCAN00088425    No changes
 *                         TnS     ESCAN00088469    Added MISRA deviation comments
 *  03.16.00   2016-07-29  CB      ESCAN00089471    No changes
 *  03.17.00   2016-08-24  Rie     ESCAN00091652    Reworked extended addressing
 *  03.18.00   2016-09-26  CB      ESCAN00053859    Removed unnecessary volatile qualifiers
 *  03.19.00   2016-11-08  TnS     ESCAN00092702    Added support for Mixed Addressing
 *  03.20.00   2017-05-16  Ach     ESCAN00095195    No changes
 *  03.21.00   2017-11-20  CB      ESCAN00097480    No changes
 *
 *  NOTE: This version has been adapted and must be used with Flash-Bootloader ONLY!
 **********************************************************************************************************************/

#ifndef __FBL_TP_H__
#define __FBL_TP_H__

#include "v_cfg.h"
#include "v_def.h"

#include "ftp_cfg.h"                /* Tool generated header file for global and local usage */

/* Set this value according to the actual version number of this module. The
 * value is used to generate the Main- and Subversion number for diagnosis.*/

/* ##V_CFG_MANAGEMENT ##CQProject : FblTp_Iso CQComponent : Implementation */
#define FBLTP_ISO_VERSION           0x0321u
#define FBLTP_ISO_RELEASE_VERSION   0x00u

/***********************************************************************************************************************
 *  TRANSPORT PROTOCOL GLOBAL RESULT CODES
 **********************************************************************************************************************/

#define kTpSuccess                                  0u    /**< Everything is fine */
#define kTpFailed                                   1u    /**< Unspecific failure */
#define kTpCanTxFailed                              2u    /**< Could not send message to CAN */
#define kTpBusy                                     3u    /**< TpTransmit while TP is running */
#define kTpTxBufferUnderrun                         4u    /**< Not enough data to send */
#define kTpTimeoutFC                                5u    /**< Timeout waiting for FlowControl */
#define kTpErrTxFCNotExpected                       9u    /**< Unexpected FC received */
#define kTpErrTxWaitFrLimitExeeded                 12u    /**< Unexpected FC received */
#define kTpErrTxOverrun                            15u    /**< TX overrun */
#define kTpErrTxFSInvalid                          16u    /**< Invalid FS received */

/* Error notification codes */
#define kTpErrRxWrongSN                             6u    /**< Wrong sequence number received in CF */
#define kTpErrRxTimeout                             7u    /**< Receive (CF, FC) Timeout occurred */
#define kTpErrRxNotIdle                             8u    /**< TP not idle */
#define kTpErrRxCFNotExpected                      10u    /**< Unexpected CF received */
#define kTpErrRxSFDL                               11u    /**< Single frame data length error (DL > possible SF_DL) */
#define kTpErrRxIllegalByteCountInBlockTransfer    13u    /**< Illegal byte count in block transfer */
#define kTpErrRxSFInvalidFormat                    14u    /**< Single frame format error */

extern MEMORY_ROM vuint8 kFblTpMainVersion;
extern MEMORY_ROM vuint8 kFblTpSubVersion;
extern MEMORY_ROM vuint8 kFblTpBugFixVersion;

/***********************************************************************************************************************
 *  HEADER PART FOR TP CHANNEL
 **********************************************************************************************************************/

#if !defined( kTpOn )
# define kTpOn    1u
#endif

#if !defined( kTpOff )
# define kTpOff   0u
#endif

/***********************************************************************************************************************
 *  CHECK ALL SWITCHES TO ISO COMPLIANCE
 **********************************************************************************************************************/

/* !!! Non-ISO compliance with FBL_TP !!! (TP_USE_CONFIRMATION_INTERRUPT == kTpOn) */

#if defined( FBL_TP_ENABLE_ISO_COMPLIANCE )
# if defined( FBL_TP_ENABLE_FLOW_STATE ) && \
     defined( FBL_TP_ENABLE_ONLY_FIRST_FC )
   /* Everything is fine */
# else
#  error "Mismatch in configuration switches - no ISO compliance"
# endif
#endif

/***********************************************************************************************************************
 *  TRANSPORT PROTOCOL GLOBAL FUNCTIONS
 **********************************************************************************************************************/

/* Start of code segment to be executed in RAM */
# define FBLTP_RAMCODE_START_SEC_CODE
# include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

void FblTpInitPowerOn(void);
vuint8 FblTpTransmit(tTpDataType count);
#if defined( MULTIPLE_RECEIVE_BUFFER )
vuint8 FblTpPrecopy(const pChipDataPtr data);
#endif
vuint8 FblTpTransmitSF(vuint8 count);
void FblTpTask(void);
void FblTpConfirmation(CanTransmitHandle txObject);

/** Functions to manipulate the receive buffer blocking state */
void FblTpResetRxBlock(void);
void FblTpSetRxBlock(void);

/* End of code segment to be executed in RAM */
# define FBLTP_RAMCODE_STOP_SEC_CODE
# include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

#if defined( FBL_TP_DISABLE_V2XX_COMPATIBILITY )
#else
/* Backward compatibility naming convention */
# define TpResetRxBlock()           FblTpResetRxBlock()
# define TpSetRxBlock()             FblTpSetRxBlock()
#endif /* FBL_TP_DISABLE_V2XX_COMPATIBILITY */

/* Macros for block size handling with max. BS-value of 255 */
/* FblTpSetRxBS: Reset counter-byte also! */
#define FblTpSetRxBS(newBS)         {\
                                       bRxBlockSize = (newBS);\
                                       bRxBSCounter = (newBS);\
                                    } /* PRQA S 3458 */ /* MD_MSR_19.4 */
#define FblTpGetRxBS()              (bRxBlockSize)

/* Macros for STmin handling */
#define FblTpSetRxSTmin(newSTmin)   (bRxSTmin = (newSTmin)) /* PRQA S 3453 */ /* MD_MSR_19.7 */
#define FblTpGetRxSTmin()           (bRxSTmin)

/***********************************************************************************************************************
 *  OSEKTP GLOBAL DATA STRUCTS
 **********************************************************************************************************************/

extern tTpDataType gbTpRxDL;
extern tTpDataType gbTpTxDL;
extern tTpDataType gbTpRxLength;

extern MEMORY_NEAR volatile vuint8 bRxBlockSize;

extern MEMORY_NEAR volatile vuint8 bRxBSCounter;

extern vuint8 bRxSTmin;

#if defined( FBL_TP_ENABLE_ISO15765_2_2 ) || \
    defined( FBL_TP_ENABLE_OVERRUN_FLAG_IN_FC )
# if defined( FBL_TP_ENABLE_ACCEPT_TOO_LARGE_DATA )
#  error "TP configuration: Useless combination of options by accepting too large data together with overrun bit support in flow-control"
# endif
#endif

# if defined( FBL_ENABLE_CAN_CONFIRMATION )
# else
#  if defined( FBL_TP_ENABLE_CONFIRMATION_INTERRUPT )
#   error "TP configuration: Usage of TP confirmation without CAN confirmation is useless."
#  endif
# endif

#endif /* __FBL_TP_H__ */

/***********************************************************************************************************************
 *  END OF FILE: FBL_TP.H
 **********************************************************************************************************************/
